[Settings]
# Which player to use? Full or environment path.
player=mpv

# Pass some player options, e.g. to set initial volume
# Mpv requires the --no-terminal option to work
player_options=--no-terminal

# Automatically play one of the available streams at startup (menu number)
autoplay=

# The directory to look for M3U files.
directory=streams

# Uncomment to manually set the language for program messages, usually needed for Windows
#language=de_DE.UTF-8

# Set to true for a more verbose output
debug=False
